apiVersion: asset.sap/v1
kind: Asset

metadata:
  name: procurement-task-mcp
  version: 1.0.0

type: mcp-server

mcpServer:
  translationFile: translation.json
  apiOrdId: sap.s4:apiResource:API_SUPPLIER_ACTIVITY_TASK_SRV:v1
