apiVersion: asset.sap/v1
kind: Asset

metadata:
  name: purchase-order-mcp
  version: 1.0.0

type: mcp-server

mcpServer:
  translationFile: translation.json
  apiOrdId: sap.s4:apiResource:API_PURCHASEORDER_2:v1
